# Generated by Django 3.1.3 on 2020-11-24 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20201124_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='amount',
        ),
        migrations.AddField(
            model_name='transaction',
            name='amount_paid',
            field=models.DecimalField(decimal_places=8, default=1, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='amount_recived',
            field=models.DecimalField(decimal_places=8, default=1, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='currency_recived',
            field=models.CharField(choices=[('PLN', 'PLN'), ('USD', 'USD'), ('BTC', 'BTC'), ('XRP', 'XRP')], default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='medal',
            field=models.CharField(blank=True, choices=[('GOLD', 'Gold'), ('SILVER', 'Silver'), ('BRONZE', 'Bronze')], max_length=10),
        ),
    ]
