# Generated by Django 3.1.3 on 2020-11-24 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20201124_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='medal',
        ),
        migrations.AddField(
            model_name='transaction',
            name='currency_paid',
            field=models.CharField(choices=[('PLN', 'PLN'), ('USD', 'USD'), ('BTC', 'BTC'), ('XRP', 'XRP'), ('ETH', 'ETH')], default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='currency_recived',
            field=models.CharField(choices=[('PLN', 'PLN'), ('USD', 'USD'), ('BTC', 'BTC'), ('XRP', 'XRP'), ('ETH', 'ETH')], max_length=3),
        ),
    ]
