# Generated by Django 3.1.3 on 2020-11-24 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20201124_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='btc_balance',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wallet',
            name='eth_balance',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wallet',
            name='pln_balance',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wallet',
            name='total_balance',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wallet',
            name='xrp_balance',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
