# Generated by Django 3.1.3 on 2020-11-24 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20201124_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='usd_balance',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
