# Generated by Django 3.1.3 on 2020-11-24 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_wallet_usd_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='btc_balance',
            field=models.DecimalField(decimal_places=8, max_digits=15),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='eth_balance',
            field=models.DecimalField(decimal_places=8, max_digits=15),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='pln_balance',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='usd_balance',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='xrp_balance',
            field=models.DecimalField(decimal_places=8, max_digits=15),
        ),
    ]
