# Generated by Django 3.1.3 on 2020-11-24 22:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20201124_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='currency_paid_price_in_usd',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='currency_recived_price_in_usd',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='transaction',
            name='dollar_price_in_pln',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wallet',
            name='total_balance',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
