# Generated by Django 3.1.3 on 2020-11-25 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20201124_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.TextField(default='testowy opis', max_length=250),
            preserve_default=False,
        ),
    ]
