# Generated by Django 3.1.3 on 2020-11-25 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_transaction_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date']},
        ),
    ]
