# Generated by Django 3.1.3 on 2020-12-01 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_auto_20201126_0042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='usd_balance',
        ),
    ]
