# Generated by Django 3.1.3 on 2020-12-01 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_remove_wallet_usd_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='currency_paid_price_in_usd',
            new_name='currency_paid_price_in_pln',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='currency_recived_price_in_usd',
            new_name='currency_recived_price_in_pln',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='currency_paid',
            field=models.CharField(choices=[('PLN', 'PLN'), ('BTC', 'BTC'), ('XRP', 'XRP'), ('ETH', 'ETH')], max_length=3),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='currency_recived',
            field=models.CharField(choices=[('PLN', 'PLN'), ('BTC', 'BTC'), ('XRP', 'XRP'), ('ETH', 'ETH')], max_length=3),
        ),
    ]
